apiVersion: v1
data:
  tls.crt: {{ .Values.detectifyChallengeApp.crt }}
  tls.key: {{ .Values.detectifyChallengeApp.key }}
kind: Secret
metadata:
  name: {{ .Values.detectifyChallengeApp.name }}-tls
type: kubernetes.io/tls
