apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.detectifyChallengeApp.name }}-app
  labels:
    app: {{ .Values.detectifyChallengeApp.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.detectifyChallengeApp.name }}
      tier: {{ .Values.detectifyChallengeApp.tier }}
  replicas: {{ .Values.detectifyChallengeApp.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.detectifyChallengeApp.name }}
        tier: {{ .Values.detectifyChallengeApp.tier }}
    spec:
      containers:
      - name: {{ .Values.detectifyChallengeApp.name }}
        image: {{ .Values.detectifyChallengeApp.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.detectifyChallengeApp.imagePort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.detectifyChallengeApp.imagePort }}