apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.challengeApp.name }}-ingress
spec:
  tls:
  - hosts:
      - {{ .Values.challengeApp.ingressHost }}
    secretName: {{ .Values.challengeApp.name }}-tls
  rules:
  - host: {{ .Values.challengeApp.ingressHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.challengeApp.name }}-service
          servicePort: {{ .Values.challengeApp.imagePort }}