name: GitHub Actions Demo
on: [push]
jobs:
  clone_repo:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1  
      with:
        repository: organization_name/repo_name
        token: ${{ secrets.ACCESS_TOKEN }}
  execute_command:
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          git clone"https://$GITHUBTOKEN@github.com/akashkaveti/terraform-samples.git" /tmp
          ls