name: GitHub Actions Demo
on: [push]
jobs:
  execute_command:
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /tmp
          echo "$GITHUBTOKEN"
          git config remote.origin.url https://"$GITHUBTOKEN"@github.com/akashkaveti/terraform-samples.git
          git clone https://"$GITHUBTOKEN"@github.com/akashkaveti/terraform-samples.git
          ls